[package]
name = "s-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.29", features = [
    "recovery",
    "rand-std",
    "hashes-std",
] }
hex = "0.4"
bytes = "1"
sha2 = "0.10.8"
sha3 = "0.10.8"
